import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script 
        src="hhttps://popup-teal-two.vercel.app/fa.js" 
        data-website-id="308961" 
        data-api-url="https://popup-teal-two.vercel.app/"
        async
    ></script>
        {children}
      </body>
    </html>
  );
}
